# Twitter
TWITTER_CONSUMER_KEY:
TWITTER_CONSUMER_SECRET:
TWITTER_ACCESS_TOKEN:
TWITTER_ACCESS_TOKEN_SECRET:
TWITTER_TEXT:

# Azure
AZURE_QUEUE:
AZURE_STORAGE_ACCT:
AZURE_QUEUE_KEY:
AZURE_ANALYTICS_URI:
AZURE_ANALYTICS_KEY:
COSMOS_DB_ENDPOINT:
COSMOS_DB_MASTERKEY:
COSMOS_DB_DATABASE:
COSMOS_DB_COLLECTION:

# Images
imageRegistry: neilpeterson
imageVersion: v2